"""Render a `MinerReport` and feed it into `.context/session-memory/`.

Writes a dedicated, miner-owned file (``failure-patterns.md``) rather than
merging into a tier the agent hand-edits (``now.md`` / ``core-memories.md``):
nothing else generates or edits this file, so a full, deterministic re-render
each call is correct and simpler than the marker-delimited non-destructive
merge headroom's ``writer.py`` performs on files a human also writes to. The
rendered body says so in its own first lines, because the file sits in a
directory the agent is otherwise told to write into.

**Why the filename is a module constant and not a `MemoryTier` member.**
`MemoryTier` is the closed alphabet of *authored* memory tiers — the files the
agent and the roll/emit machinery read and rewrite. This one is a generated
artifact that no tier consumer reads, so adding it to that enum would make
`ensure_memory_store` stub it and imply a lifecycle it does not have. The
convention's target is stringly-typed alphabets used across the codebase; this
name is used in exactly one place, here.

**Sanitization is not optional.** Everything rendered goes through
`scope.sanitize_signature` first: this file is git-tracked, and a signature is
built from a caller's own tool input, so it arrives carrying absolute host
paths. See `scope.py`.
"""

from __future__ import annotations

from pathlib import Path

from ...atomic_io import write_text_atomic
from ..store import memory_dir
from .enums import DEFAULT_MIN_OCCURRENCES
from .models import MinerReport
from .scope import sanitize_signature

FAILURE_PATTERNS_FILENAME = "failure-patterns.md"

_GENERATED_MARKER = (
    "<!-- generated by dummyindex's failure-miner; edits here are "
    "overwritten on the next run -->"
)


def render_report(report: MinerReport, *, repo_root: Path) -> str:
    """Deterministic markdown body for one `MinerReport`.

    Pure function of `report` and `repo_root` — no timestamps, no ordering
    that isn't already fixed by `signatures.detect_repeated_signatures` — so
    the same report always renders to the same bytes.
    """
    coverage = f"Scanned {report.scanned_sessions} transcript(s)"
    if report.unreadable_sessions:
        coverage += f" ({report.unreadable_sessions} unreadable, skipped)"
    coverage += f"; {len(report.signatures)} pattern(s) met the threshold."

    lines = [
        _GENERATED_MARKER,
        "",
        "# Failure & loop patterns (auto-mined)",
        "",
        "Deterministically mined from this repo's local transcripts: tool "
        f"calls whose canonical signature recurred {DEFAULT_MIN_OCCURRENCES}+ "
        "times within one transcript. No model call, no network. Paths are "
        "repo-relative; anything outside this repo is redacted, and no "
        "excerpt of tool output is kept — see "
        "`dummyindex/context/domains/memory/miner/`.",
        "",
        coverage,
    ]
    if not report.signatures:
        lines.append("")
        lines.append("_No repeated failure/loop signatures found._")
    else:
        for sig in report.signatures:
            safe = sanitize_signature(sig.signature, repo_root=repo_root)
            lines.append("")
            lines.append(
                f"- **{sig.tool_name}** `{safe}` — {sig.kind.value}, "
                f"{sig.occurrences}x, ~{sig.estimated_wasted_tokens} tokens wasted"
            )
    return "\n".join(lines).rstrip("\n") + "\n"


def write_report(context_dir: Path, report: MinerReport, *, repo_root: Path) -> Path:
    """Render and atomically write the report to its session-memory file."""
    path = memory_dir(context_dir) / FAILURE_PATTERNS_FILENAME
    write_text_atomic(path, render_report(report, repo_root=repo_root))
    return path
