"""Repo/packaging hygiene guards for the dummyindex source checkout.

Two classes of rot these tests turn from silent into red:

1. Packaging dirs (``dummyindex.egg-info/``, ``build/``) *committed* to the
   repo — ``importlib.metadata`` resolves the repo-root egg-info first under
   ``python3 -m``, so a tracked stale egg-info makes ``dummyindex --version``
   (and every installed __VERSION__ stamp) report the *old* version, and a
   tracked ``build/lib`` re-bundles deleted modules into the next wheel. We
   only flag dirs that are *tracked by git*: a freshly-generated egg-info from
   the normal ``pip install -e .`` (gitignored, carries the current version) is
   harmless and is exactly what CI produces, so filesystem presence alone must
   never fail the suite.
2. Realistic secret-shaped placeholders sneaking into shipped skill prompts —
   consumer repos run secret scanners over committed ``.context``/skill docs,
   so shipped markdown must only ever use obviously-fake placeholders
   (``<API_KEY>``, ``YOUR-TOKEN-HERE``), never ``ghp_…`` / ``sk-…`` / ``AKIA…``
   shapes.
"""

from __future__ import annotations

import re
import subprocess

import pytest

from tests.paths import REPO_ROOT

_IS_SOURCE_CHECKOUT = (REPO_ROOT / "pyproject.toml").is_file() and (
    REPO_ROOT / ".git"
).exists()

_STALE_PACKAGING_DIRS = ("dummyindex.egg-info", "build")

# Realistic credential shapes that trip secret scanners (detect-secrets,
# gitleaks). Word-bounded + length-gated so prose like "task-dependent"
# can't match.
_SECRET_SHAPES = re.compile(
    r"\b(?:ghp_[A-Za-z0-9]{16,}|sk-[A-Za-z0-9]{16,}|AKIA[0-9A-Z]{12,})"
)


def _git_tracks_anything_under(rel_dir: str) -> bool:
    """True if git tracks any path under ``rel_dir`` (i.e. it was committed)."""
    result = subprocess.run(
        ["git", "ls-files", "--", rel_dir],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode == 0 and bool(result.stdout.strip())


@pytest.mark.unit
@pytest.mark.skipif(not _IS_SOURCE_CHECKOUT, reason="not a git source checkout")
def test_no_stale_local_packaging_dirs() -> None:
    # Flag only *committed* artefacts — a gitignored egg-info generated by the
    # normal ``pip install -e .`` (as CI does) is harmless and must not fail.
    stale = [d for d in _STALE_PACKAGING_DIRS if _git_tracks_anything_under(d)]
    assert not stale, (
        f"packaging artefacts {stale} are tracked by git and shadow the real "
        "package version: importlib.metadata finds the repo-root egg-info "
        "first, so `python3 -m dummyindex --version` (and every installed "
        "__VERSION__ stamp) reports the old version, and a committed build/lib "
        "re-bundles deleted modules into the next wheel. Fix: "
        "`git rm -r --cached dummyindex.egg-info build && rm -rf "
        "dummyindex.egg-info build`."
    )


@pytest.mark.unit
def test_shipped_skill_markdown_has_no_realistic_secret_shapes() -> None:
    skills_dir = REPO_ROOT / "dummyindex" / "skills"
    offenders: list[str] = []
    for md in sorted(skills_dir.rglob("*.md*")):
        if not md.is_file():
            continue
        match = _SECRET_SHAPES.search(md.read_text(encoding="utf-8"))
        if match:
            offenders.append(f"{md.relative_to(REPO_ROOT)}: {match.group(0)[:12]}…")
    assert not offenders, (
        "shipped skill markdown contains realistic secret-shaped strings "
        f"(consumer secret scanners will fail CI on them): {offenders}"
    )
