"""Ack store — user-recorded dismissals for drift rows (``drift-ack`` verb).

A row that is a false positive *for this machine/workflow* would otherwise
resurface every session with no way to act on it. An **ack** records the
judgement "feature ``X``'s file ``Y`` at blob sha ``Z`` is known-good" as an
append-only entry in the gitignored cache at
``.context/cache/drift-acks.json``:

    {feature_id, path?, acked_sha, reason?, ts}

Suppression semantics live with the consumer (``context/drift.py``): an ack
suppresses a drift row only while the file's current sha still equals
``acked_sha`` — any edit auto-expires it, because a changed file is real work
again. On-git repos record git blob shas; off-git repos work identically using
content sha256 instead.

Storage mirrors the corrupt-tolerant cache pattern of
``gc/anchor.py:_load_memo``: a missing / malformed / non-dict payload reads
back as empty and never raises, while every write goes through
``write_text_atomic`` (tmp + replace) so a concurrent reader never observes a
half-written store. Nothing here decides policy — read, append, clear.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from .atomic_io import write_text_atomic

# Gitignored scratch tier (same as ``cache/manifest.json``): per-machine
# dismissal state, never committed, regenerated by use.
ACKS_REL = Path("cache") / "drift-acks.json"
ACKS_SCHEMA_VERSION = 1


def acks_path(context_dir: Path) -> Path:
    """Path to the ack store under ``.context/cache/``."""
    return context_dir / ACKS_REL


def read_acks(context_dir: Path) -> list[dict]:
    """Every recorded ack entry, oldest first; ``[]`` when none/unreadable.

    Corrupt-tolerant exactly like ``gc/anchor.py:_load_memo``: a missing file,
    a ``JSONDecodeError``, a non-dict payload, or a missing/non-list
    ``acks`` key all degrade to ``[]`` — never a raise. Non-dict entries are
    dropped so consumers can index fields safely.
    """
    path = acks_path(context_dir)
    if not path.exists():
        return []
    try:
        obj = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, ValueError, OSError):
        return []
    if not isinstance(obj, dict):
        return []
    raw = obj.get("acks")
    if not isinstance(raw, list):
        return []
    return [entry for entry in raw if isinstance(entry, dict)]


def append_ack(
    context_dir: Path,
    *,
    feature_id: str,
    acked_sha: str,
    path: str | None = None,
    reason: str | None = None,
    now: datetime | None = None,
) -> dict:
    """Append one ack entry atomically and return it.

    Append-only by contract: existing entries are never rewritten or pruned,
    so a suppressed row keeps its provenance. ``now`` is injectable for
    testability (defaults to wall-clock).
    """
    entry: dict = {
        "feature_id": feature_id,
        "path": path,
        "acked_sha": acked_sha,
        "reason": reason,
        "ts": (now or datetime.now()).isoformat(),
    }
    acks = read_acks(context_dir)
    acks.append(entry)
    _write(context_dir, acks)
    return entry


def clear_acks(context_dir: Path) -> int:
    """Drop every ack entry; returns how many were removed (idempotent).

    The store file itself stays behind (rewritten to an empty list) so the
    schema marker survives; the next append starts fresh.
    """
    acks = read_acks(context_dir)
    count = len(acks)
    if count:
        _write(context_dir, [])
    return count


def _write(context_dir: Path, acks: list[dict]) -> None:
    payload = json.dumps({"schema_version": ACKS_SCHEMA_VERSION, "acks": acks}, indent=2)
    write_text_atomic(acks_path(context_dir), payload + "\n")
