"""Manage the dummyindex section in CLAUDE.md.

Idempotent: re-running replaces the existing block in place, preserves
surrounding content, and raises on unbalanced or duplicate markers.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

BEGIN_MARKER = (
    "<!-- dummyindex:begin (managed — do not hand-edit; "
    "regenerate with `dummyindex context bootstrap`) -->"
)
END_MARKER = "<!-- dummyindex:end -->"


class UnbalancedMarkersError(ValueError):
    """Raised when CLAUDE.md has malformed dummyindex markers."""


_V0_BLOCK_BODY = """\
# dummyIndex — Context Engine

This project has a `.context/` folder generated by dummyIndex. **It is the canonical source of project context — read it before grepping, before opening files at random, before asking the user clarifying questions you could answer from the index.**

## First action on any non-trivial request

Read `.context/HOW_TO_USE.md`. It tells you exactly which index file answers which type of question. The short version is below.

## Index files (consult in this order)

| Question | File |
|---|---|
| What is this project? | `.context/PROJECT.md` |
| What's the high-level layout? | `.context/architecture/overview.md` |
| Where is `X` defined? | `.context/map/symbols.json` (every symbol has `path` + `range`) |
| Full hierarchical map | `.context/tree.json` (walk it — don't load wholesale) |
| Every source file | `.context/map/files.json` |
| Cross-symbol relationships, communities, god-nodes | `.context/graph/graph.json` (open `graph/graph.html` in a browser for the interactive view) |
| Naming style for new code | `.context/conventions/naming.md` |

## Task-specific recipes

When the user asks you to **add**, **fix**, **migrate**, or **refactor**, the matching playbook in `.context/playbooks/` walks through the canonical approach:

- `playbooks/add-feature.md` — new capability
- `playbooks/add-endpoint.md` — new HTTP endpoint
- `playbooks/add-migration.md` — database migration
- `playbooks/fix-bug.md` — diagnose + fix
- `playbooks/refactor.md` — refactor without behavior change

Each playbook references the specific index files to consult at each step.

## Rules

- **Honor `conventions/naming.md`** for every new file / class / function you create.
- **Don't write to `.context/`** by hand — it regenerates on rebuild.
- **If the index disagrees with the code, the code wins** — note the discrepancy and run `dummyindex context rebuild --changed`.
- **Cache (`.context/cache/`) is per-machine** — gitignored. Never reference it in answers.

This is dummyIndex v0 — deterministic passive context. LLM-enriched summaries and MCP-driven routing arrive in v0.1 / v0.2; see `BRIEF.md` at the repo root for the roadmap."""


def generate_managed_block() -> str:
    """Return the body of the managed block (without begin/end markers)."""
    return _V0_BLOCK_BODY


def bootstrap_claude_md(path: Path, *, block_body: Optional[str] = None) -> str:
    """Write or update the managed block at `path`.

    Idempotent. Preserves surrounding content. Returns the final file content.
    """
    body = (block_body if block_body is not None else generate_managed_block()).rstrip()
    managed = f"{BEGIN_MARKER}\n{body}\n{END_MARKER}"

    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        new_content = managed + "\n"
        _atomic_write(path, new_content)
        return new_content

    existing = path.read_text(encoding="utf-8")
    begin_count = existing.count(BEGIN_MARKER)
    end_count = existing.count(END_MARKER)

    if begin_count != end_count:
        raise UnbalancedMarkersError(
            f"{path} has {begin_count} begin marker(s) but {end_count} end "
            "marker(s). Resolve manually before re-running."
        )
    if begin_count > 1:
        raise UnbalancedMarkersError(
            f"{path} has {begin_count} dummyindex managed blocks; expected 0 or 1."
        )

    if begin_count == 0:
        new_content = _append_block(existing, managed)
    else:
        new_content = _replace_block(existing, managed)

    _atomic_write(path, new_content)
    return new_content


def _append_block(existing: str, managed: str) -> str:
    if not existing:
        return managed + "\n"
    if existing.endswith("\n\n"):
        return existing + managed + "\n"
    if existing.endswith("\n"):
        return existing + "\n" + managed + "\n"
    return existing + "\n\n" + managed + "\n"


def _replace_block(existing: str, managed: str) -> str:
    begin_idx = existing.index(BEGIN_MARKER)
    end_idx = existing.index(END_MARKER) + len(END_MARKER)
    return existing[:begin_idx] + managed + existing[end_idx:]


def _atomic_write(path: Path, content: str) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)
