"""Generate .context/INDEX.md and .context/PROJECT.md.

Deterministic — no LLM. Pulls structured data from pyproject.toml /
package.json / README.md / meta.json (whichever exist).
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from dummyindex.context.meta import Meta
from dummyindex.context.source_docs import DocCatalog

_FILE_DESCRIPTIONS: dict[str, str] = {
    "PROJECT.md": "One-page project summary (mission, languages, dependencies).",
    "HOW_TO_USE.md": "Agent-facing guide — read first to learn how to navigate this folder.",
    "tree.json": "PageIndex-style hierarchical reasoning tree (project → dir → file → class → method).",
    "map/files.json": "Every source file with language, size, LOC, and SHA-256 fingerprint.",
    "map/symbols.json": "Every class / function / method with path, line, parent, exported flag.",
    "conventions/naming.md": "Derived naming rules (per language, per symbol kind).",
    "conventions/naming.json": "Machine-readable form of naming.md.",
    "architecture/overview.md": "Top-level architecture summary (directories, role hints, stack).",
    "playbooks/add-feature.md": "Recipe — adding a new capability.",
    "playbooks/add-endpoint.md": "Recipe — adding an HTTP endpoint.",
    "playbooks/add-migration.md": "Recipe — adding a database migration.",
    "playbooks/fix-bug.md": "Recipe — diagnosing and fixing a bug.",
    "playbooks/refactor.md": "Recipe — refactoring without behavior change.",
    "features/INDEX.json": "Feature list (machine-readable). Start here for behavioral navigation.",
    "features/INDEX.md": "Feature list (human table).",
    "features/HOW_TO_NAVIGATE.md": "How to walk features/ programmatically — the agent's behavioral entry point.",
    "features/symbol-graph.json": "Raw NetworkX knowledge graph (every symbol, every call/contains/imports edge, Leiden communities). The input to feature scaffolding.",
    "features/graph.json": "Denormalized for the HTML viewer — folder · file · feature · flow nodes.",
    "features/graph.html": "Interactive D3 viewer over features/graph.json.",
    "features/COMMUNITIES.md": "Community + god-node report (replaces old graph/GRAPH_REPORT.md).",
    "meta.json": "Run metadata: schema version, languages, file/symbol counts.",
    "source-docs/INDEX.json": "Catalog of prose docs (README, CHANGELOG, docs/, ADR/, --docs paths) with broken-ref + age staleness signals.",
    "source-docs/INDEX.md": "Human-readable doc catalog. Advisory — every entry carries a confidence (high/medium/low).",
}


def refresh_index_md(context_dir: Path) -> tuple[str, ...]:
    """Rebuild ``<context_dir>/INDEX.md`` from what's actually on disk.

    Walks the folder, collects every file path relative to ``context_dir``,
    excludes the managed cache + .gitignore + temp files + INDEX.md itself,
    and regenerates the index. Use after the `/dummyindex` skill renames
    feature folders — the original INDEX.md was written at ingest time and
    its `features/community-N/...` paths will no longer match disk.

    Returns the sorted list of relative paths the new INDEX.md covers.
    """
    context_dir = context_dir.resolve()
    rels: list[str] = []
    for p in context_dir.rglob("*"):
        if not p.is_file():
            continue
        rel = p.relative_to(context_dir).as_posix()
        if (
            rel == "INDEX.md"
            or rel.startswith("cache/")
            or rel.endswith(".tmp")
            or rel == ".gitignore"
        ):
            continue
        rels.append(rel)
    rels.sort()
    write_index_md(context_dir / "INDEX.md", generate_index_md(rels))
    return tuple(rels)


def generate_index_md(available: list[str]) -> str:
    """A hand-readable TOC of what's in .context/."""
    lines: list[str] = ["# .context/", ""]
    lines.append(
        "This folder is generated by **dummyIndex**. It is the canonical context "
        "for AI coding agents working on this project. Files are written "
        "deterministically — no LLM calls in v0."
    )
    lines.append("")
    lines.append("## Files in this run")
    lines.append("")
    for rel in available:
        desc = _FILE_DESCRIPTIONS.get(rel)
        lines.append(f"- `{rel}`" + (f" — {desc}" if desc else ""))
    lines.append("")
    lines.append("## How to use")
    lines.append("")
    lines.append(
        "**Agents:** read `PROJECT.md` for project context, then navigate via "
        "`tree.json` and `map/symbols.json` for specific work. Honor "
        "`conventions/naming.md` when adding new code."
    )
    lines.append("")
    lines.append(
        "**Humans:** start with `PROJECT.md`. The `tree.json` and `map/*.json` "
        "files are dense — use them programmatically or read sparingly."
    )
    lines.append("")
    lines.append("## Rebuild")
    lines.append("")
    lines.append(
        "After non-trivial code changes: `dummyindex context rebuild --changed` "
        "(incremental) or `dummyindex context rebuild` (full)."
    )
    lines.append("")
    return "\n".join(lines)


def generate_project_md(
    repo_root: Path,
    meta: Meta,
    *,
    doc_catalog: Optional[DocCatalog] = None,
) -> str:
    """A one-page project summary derived from manifests + docs + meta.

    When ``doc_catalog`` is provided, the description prefers the highest-
    confidence README/intro doc in the catalog over the raw first
    paragraph, and an "Existing documentation" section is appended that
    points at ``source-docs/INDEX.md``.
    """
    name = repo_root.name
    description = ""
    version = ""
    scripts: dict[str, str] = {}

    py = _read_pyproject(repo_root)
    if py:
        name = py.get("name") or name
        description = py.get("description") or description
        version = py.get("version") or version
        scripts = py.get("scripts") or {}

    pkg = _read_package_json(repo_root)
    if pkg:
        if not py:
            name = pkg.get("name") or name
        if not description:
            description = pkg.get("description", "") or description
        if not version:
            version = pkg.get("version", "") or version

    if not description:
        description = _description_from_catalog(doc_catalog, repo_root) or ""
    if not description:
        readme = _read_readme_first_para(repo_root)
        if readme:
            description = readme

    lines: list[str] = [f"# {name}", ""]
    if version:
        lines.append(f"_Version {version}_")
        lines.append("")
    if description:
        lines.append(description)
        lines.append("")

    lines.append("## At a glance")
    lines.append("")
    if meta.languages:
        lines.append(f"- **Languages:** {', '.join(meta.languages)}")
    lines.append(f"- **Files:** {meta.file_count}")
    lines.append(f"- **Symbols:** {meta.symbol_count}")
    if doc_catalog is not None:
        lines.append(f"- **Documents:** {len(doc_catalog.docs)}")
    lines.append(f"- **Root:** `{meta.root}`")
    lines.append(f"- **Last indexed:** {meta.updated_at}")
    lines.append(f"- **dummyIndex version:** {meta.dummyindex_version}")
    lines.append("")

    if scripts:
        lines.append("## Entry points")
        lines.append("")
        for entry, target in sorted(scripts.items()):
            lines.append(f"- `{entry}` → `{target}`")
        lines.append("")

    if doc_catalog is not None and doc_catalog.docs:
        lines.extend(_render_doc_section(doc_catalog))

    return "\n".join(lines).rstrip() + "\n"


def _description_from_catalog(
    catalog: Optional[DocCatalog],
    repo_root: Path,
) -> Optional[str]:
    """Pull the best available description from the highest-confidence README."""
    if catalog is None:
        return None
    candidates = [
        d for d in catalog.docs
        if not d.is_external and d.confidence != "low"
        and d.path.lower().split("/")[-1].startswith("readme")
    ]
    if not candidates:
        # Fall back to any high-confidence doc that has a meaningful title.
        candidates = [
            d for d in catalog.docs
            if not d.is_external and d.confidence == "high" and d.title
        ]
    for d in candidates:
        try:
            text = (repo_root / d.path).read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        para = _first_paragraph(text)
        if para:
            return para
    return None


def _first_paragraph(text: str) -> Optional[str]:
    """First non-heading paragraph from a markdown-like body."""
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            text = text[end + 4:]
    paragraph_lines: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            if paragraph_lines:
                return " ".join(paragraph_lines).strip()
            continue
        if stripped.startswith("#"):
            if paragraph_lines:
                return " ".join(paragraph_lines).strip()
            continue
        paragraph_lines.append(stripped)
    if paragraph_lines:
        return " ".join(paragraph_lines).strip()
    return None


def _render_doc_section(catalog: DocCatalog) -> list[str]:
    """The "Existing documentation" section appended to PROJECT.md."""
    high = [d for d in catalog.docs if d.confidence == "high"]
    medium = [d for d in catalog.docs if d.confidence == "medium"]
    low = [d for d in catalog.docs if d.confidence == "low"]
    lines = [
        "## Existing documentation",
        "",
        (
            f"_{len(catalog.docs)} doc(s) catalogued from this repo "
            f"(plus {len(catalog.extra_doc_roots)} external root(s)). "
            f"See `source-docs/INDEX.md` for the full table — including "
            f"per-doc confidence and broken-reference detail._"
        ),
        "",
        (
            "**Advisory:** docs drift faster than code. The catalog grades "
            "each doc against the current AST extraction:"
        ),
        "",
        f"- **High confidence:** {len(high)} — safe to quote, but still cross-check.",
        f"- **Medium confidence:** {len(medium)} — verify references before trusting.",
        f"- **Low confidence:** {len(low)} — historical context only; do not quote.",
        "",
    ]
    notable = [d for d in high if d.title and not d.is_external][:5]
    if notable:
        lines.append("**Where to look first:**")
        lines.append("")
        for d in notable:
            lines.append(f"- [`{d.path}`](../{d.path}) — {d.title}")
        lines.append("")
    if catalog.extra_doc_roots:
        lines.append("**External doc roots (passed via `--docs`):**")
        lines.append("")
        for root in catalog.extra_doc_roots:
            lines.append(f"- `{root}`")
        lines.append("")
    return lines


def write_index_md(path: Path, content: str) -> None:
    _atomic_write(path, content)


def write_project_md(path: Path, content: str) -> None:
    _atomic_write(path, content)


# --- Manifest helpers --------------------------------------------------------


def _read_pyproject(root: Path) -> Optional[dict]:
    path = root / "pyproject.toml"
    if not path.exists():
        return None
    try:
        import tomllib
    except ImportError:
        try:
            import tomli as tomllib  # type: ignore
        except ImportError:
            return None
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
    project = data.get("project", {}) or {}
    return {
        "name": project.get("name"),
        "description": project.get("description"),
        "version": project.get("version"),
        "scripts": project.get("scripts", {}) or {},
    }


def _read_package_json(root: Path) -> Optional[dict]:
    path = root / "package.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _read_readme_first_para(root: Path) -> Optional[str]:
    for candidate in ("README.md", "readme.md", "README.rst"):
        path = root / candidate
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        if text.startswith("---"):
            end = text.find("\n---", 3)
            if end != -1:
                text = text[end + 4:]
        paragraph_lines: list[str] = []
        for line in text.splitlines():
            stripped = line.strip()
            if not stripped:
                if paragraph_lines:
                    return " ".join(paragraph_lines).strip()
                continue
            if stripped.startswith("#"):
                if paragraph_lines:
                    return " ".join(paragraph_lines).strip()
                continue
            paragraph_lines.append(stripped)
        if paragraph_lines:
            return " ".join(paragraph_lines).strip()
    return None


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)
