"""Generate .context/INDEX.md and .context/PROJECT.md.

Deterministic — no LLM. Pulls structured data from pyproject.toml /
package.json / README.md / meta.json (whichever exist).
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from dummyindex.context.meta import Meta

_FILE_DESCRIPTIONS: dict[str, str] = {
    "PROJECT.md": "One-page project summary (mission, languages, dependencies).",
    "tree.json": "PageIndex-style hierarchical reasoning tree (project → dir → file → class → method).",
    "map/files.json": "Every source file with language, size, LOC, and SHA-256 fingerprint.",
    "map/symbols.json": "Every class / function / method with path, line, parent, exported flag.",
    "conventions/naming.md": "Derived naming rules (per language, per symbol kind).",
    "conventions/naming.json": "Machine-readable form of naming.md.",
    "meta.json": "Run metadata: schema version, languages, file/symbol counts.",
}


def generate_index_md(available: list[str]) -> str:
    """A hand-readable TOC of what's in .context/."""
    lines: list[str] = ["# .context/", ""]
    lines.append(
        "This folder is generated by **dummyIndex**. It is the canonical context "
        "for AI coding agents working on this project. Files are written "
        "deterministically — no LLM calls in v0."
    )
    lines.append("")
    lines.append("## Files in this run")
    lines.append("")
    for rel in available:
        desc = _FILE_DESCRIPTIONS.get(rel)
        lines.append(f"- `{rel}`" + (f" — {desc}" if desc else ""))
    lines.append("")
    lines.append("## How to use")
    lines.append("")
    lines.append(
        "**Agents:** read `PROJECT.md` for project context, then navigate via "
        "`tree.json` and `map/symbols.json` for specific work. Honor "
        "`conventions/naming.md` when adding new code."
    )
    lines.append("")
    lines.append(
        "**Humans:** start with `PROJECT.md`. The `tree.json` and `map/*.json` "
        "files are dense — use them programmatically or read sparingly."
    )
    lines.append("")
    lines.append("## Rebuild")
    lines.append("")
    lines.append(
        "After non-trivial code changes: `dummyindex context rebuild --changed` "
        "(incremental) or `dummyindex context rebuild` (full)."
    )
    lines.append("")
    return "\n".join(lines)


def generate_project_md(repo_root: Path, meta: Meta) -> str:
    """A one-page project summary derived from manifests + README + meta."""
    name = repo_root.name
    description = ""
    version = ""
    scripts: dict[str, str] = {}

    py = _read_pyproject(repo_root)
    if py:
        name = py.get("name") or name
        description = py.get("description") or description
        version = py.get("version") or version
        scripts = py.get("scripts") or {}

    pkg = _read_package_json(repo_root)
    if pkg:
        if not py:
            name = pkg.get("name") or name
        if not description:
            description = pkg.get("description", "") or description
        if not version:
            version = pkg.get("version", "") or version

    if not description:
        readme = _read_readme_first_para(repo_root)
        if readme:
            description = readme

    lines: list[str] = [f"# {name}", ""]
    if version:
        lines.append(f"_Version {version}_")
        lines.append("")
    if description:
        lines.append(description)
        lines.append("")

    lines.append("## At a glance")
    lines.append("")
    if meta.languages:
        lines.append(f"- **Languages:** {', '.join(meta.languages)}")
    lines.append(f"- **Files:** {meta.file_count}")
    lines.append(f"- **Symbols:** {meta.symbol_count}")
    lines.append(f"- **Root:** `{meta.root}`")
    lines.append(f"- **Last indexed:** {meta.updated_at}")
    lines.append(f"- **dummyIndex version:** {meta.dummyindex_version}")
    lines.append("")

    if scripts:
        lines.append("## Entry points")
        lines.append("")
        for entry, target in sorted(scripts.items()):
            lines.append(f"- `{entry}` → `{target}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_index_md(path: Path, content: str) -> None:
    _atomic_write(path, content)


def write_project_md(path: Path, content: str) -> None:
    _atomic_write(path, content)


# --- Manifest helpers --------------------------------------------------------


def _read_pyproject(root: Path) -> Optional[dict]:
    path = root / "pyproject.toml"
    if not path.exists():
        return None
    try:
        import tomllib
    except ImportError:
        try:
            import tomli as tomllib  # type: ignore
        except ImportError:
            return None
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
    project = data.get("project", {}) or {}
    return {
        "name": project.get("name"),
        "description": project.get("description"),
        "version": project.get("version"),
        "scripts": project.get("scripts", {}) or {},
    }


def _read_package_json(root: Path) -> Optional[dict]:
    path = root / "package.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _read_readme_first_para(root: Path) -> Optional[str]:
    for candidate in ("README.md", "readme.md", "README.rst"):
        path = root / candidate
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        if text.startswith("---"):
            end = text.find("\n---", 3)
            if end != -1:
                text = text[end + 4:]
        paragraph_lines: list[str] = []
        for line in text.splitlines():
            stripped = line.strip()
            if not stripped:
                if paragraph_lines:
                    return " ".join(paragraph_lines).strip()
                continue
            if stripped.startswith("#"):
                if paragraph_lines:
                    return " ".join(paragraph_lines).strip()
                continue
            paragraph_lines.append(stripped)
        if paragraph_lines:
            return " ".join(paragraph_lines).strip()
    return None


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)
