"""Agent-facing instruction generators for `.context/`.

- `HOW_TO_USE.md`        — Claude-facing navigation guide.
- `architecture/overview.md` — deterministic top-level architecture summary.
- `playbooks/*.md`       — task-specific recipes referencing `.context/` files.

All generators are pure: no LLM, no I/O beyond returning strings.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from dummyindex.context.maps import FilesMap, SymbolsMap
from dummyindex.context.meta import Meta
from dummyindex.context.source_docs import DocCatalog, DocEntry


# --- HOW_TO_USE.md -----------------------------------------------------------


_HOW_TO_USE = """\
# How to use `.context/`

This folder is the project's **canonical machine-readable context** for AI coding agents (Claude Code, Cursor, Codex, Aider). It is generated by dummyIndex and refreshed by `dummyindex context rebuild --changed`.

## Read this folder *first* for any non-trivial work

Before grepping, reading files, or asking the user for context, consult these in order:

| Question | Look at |
|---|---|
| "What is this project?" | `PROJECT.md` |
| "What's the layout?" | `architecture/overview.md`, then `tree.json` |
| "How does feature `Z` work?" / "What's the flow when…?" | **Start at `features/INDEX.json`** — then `features/<feature-id>/feature.json` + `features/<feature-id>/README.md`. Drill into `architecture.md` / `implementation.md` / `data-model.md` / `security.md` / `product.md` for the relevant domain. See `features/HOW_TO_NAVIGATE.md`. |
| "Where is `X` defined?" | `map/symbols.json` — every class / function / method has `path` + `range` |
| "What files contain `Y`?" | `map/files.json` — full file inventory with language + size |
| "How does `X` relate to `Y`?" | `features/symbol-graph.json` — NetworkX graph with `contains`, `method`, `inherits`, `imports`, `calls` edges + Leiden communities |
| "Communities / god-nodes / hidden dependencies?" | `features/COMMUNITIES.md` |
| "What's the naming style?" | `conventions/naming.md` — honor this when adding new code |
| "How is code grouped into folders?" | `conventions/folder-organization.md` |
| "What patterns / idioms does this repo use?" | `conventions/coding-practices.md` |
| "How are tests written here?" | `conventions/testing.md` |
| "How does this repo talk to its database?" | `conventions/data-access.md` |
| "How do I add / change / fix X?" | `playbooks/` — task-specific recipes |

## Retrieval principle: walk the tree, don't grep

This index uses **PageIndex-style reasoning-based retrieval**. The procedure for any non-trivial question:

1. Read `features/INDEX.json` (the table of contents).
2. Reason over the names + summaries. Pick 1–3 features the task touches.
3. Read the chosen `feature.json` + `README.md`.
4. Drill into the domain section (`architecture.md` / `implementation.md` / `data-model.md` / `security.md` / `product.md`).
5. Follow `path:range` citations to source when you need to verify.

**Never grep the source tree first.** The tree has already been mapped; reasoning over the map beats string-matching the source.

## Concrete examples

**Asked to add a new feature?**
Read `playbooks/add-feature.md`. It walks through: check for duplicates in `map/symbols.json`, mirror an existing feature's structure (find via `tree.json`), honor `conventions/naming.md`, write tests first.

**Asked to find or modify something specific?**
Don't grep blindly. `map/symbols.json` has every symbol's `path:range`; load it once, find the match, jump straight to the code.

**Asked an architectural question?**
Start with `PROJECT.md` + `architecture/overview.md`. Most questions answer themselves at that level. Drill into `tree.json` only if you need finer detail.

**Doing a rename or refactor?**
`map/symbols.json` gives you every site to consider. Combine with conventional grep for callers.

## When the index is wrong

The code is the source of truth. If the index disagrees with what you see in a file, trust the file and re-run:

```
dummyindex context rebuild --changed
```

That re-hashes every source file and rebuilds only the changed bits.

## Feature-oriented navigation

`features/` is the **behavioral** view of the codebase (vs. `tree.json` which is the structural view). Start with `features/INDEX.json` when the user asks "how does X work?" or "what's the flow when…?" — it points at per-feature `feature.json` + `flows/<flow-id>.json` so you can answer without grepping. Folder names get renamed during enrichment but `feature_id` is stable, so always navigate by ID.

## Conventions for agents

- **Don't write to `.context/` by hand.** All files are regenerated on rebuild.
- **`cache/` is per-machine** — gitignored. Never reference it.
- **Always check `conventions/naming.md`** before naming a new symbol or file.
"""


def generate_how_to_use_md() -> str:
    return _HOW_TO_USE


# --- architecture/overview.md ------------------------------------------------


_DIR_ROLE_HINTS: dict[str, str] = {
    "test": "test suite",
    "tests": "test suite",
    "spec": "test suite",
    "specs": "test suite",
    "src": "source code",
    "lib": "library code",
    "app": "application code",
    "apps": "application code",
    "docs": "documentation",
    "doc": "documentation",
    "migrations": "database migrations",
    "migration": "database migrations",
    "db": "database layer",
    "database": "database layer",
    "schema": "database schemas",
    "schemas": "database schemas",
    "models": "data models",
    "model": "data models",
    "api": "HTTP / API surface",
    "routes": "HTTP routes",
    "handlers": "request handlers",
    "controllers": "request handlers",
    "components": "UI components",
    "pages": "UI pages",
    "views": "UI views",
    "utils": "utility helpers",
    "util": "utility helpers",
    "helpers": "utility helpers",
    "services": "business-logic services",
    "service": "business-logic services",
    "cli": "CLI commands",
    "commands": "CLI commands",
    "workers": "background workers / jobs",
    "jobs": "background jobs",
    "scripts": "operational scripts",
    "config": "configuration",
    "configs": "configuration",
    "infra": "infrastructure / deployment",
    "infrastructure": "infrastructure / deployment",
    "deploy": "deployment",
    "k8s": "kubernetes manifests",
    "terraform": "terraform / IaC",
    "static": "static assets",
    "public": "public / static assets",
    "assets": "static assets",
    "fixtures": "test fixtures",
    "examples": "examples",
    "tools": "development tools",
}


@dataclass(frozen=True)
class _DirSummary:
    name: str
    role_hint: Optional[str]
    file_count: int
    languages: tuple[str, ...]
    symbol_count: int


def generate_architecture_overview_md(
    repo_root: Path,
    files_map: FilesMap,
    symbols_map: SymbolsMap,
    meta: Meta,
    *,
    doc_catalog: Optional[DocCatalog] = None,
) -> str:
    by_dir = _group_files_by_top_level_dir(files_map)
    symbols_by_dir = _group_symbols_by_top_level_dir(symbols_map)

    summaries: list[_DirSummary] = []
    for dirname in sorted(by_dir):
        files = by_dir[dirname]
        langs = tuple(sorted({f.language for f in files if f.language}))
        summaries.append(
            _DirSummary(
                name=dirname,
                role_hint=_role_hint_for(dirname),
                file_count=len(files),
                languages=langs,
                symbol_count=len(symbols_by_dir.get(dirname, ())),
            )
        )

    lines: list[str] = ["# Architecture overview", ""]
    lines.append(
        "Auto-derived from the directory layout and AST extraction. "
        "Heuristic role hints come from common directory naming patterns."
    )
    lines.append("")

    lines.append("## Stack")
    lines.append("")
    if meta.languages:
        lines.append(f"- **Languages:** {', '.join(meta.languages)}")
    lines.append(f"- **Files:** {meta.file_count}")
    lines.append(f"- **Symbols:** {meta.symbol_count}")
    lines.append("")

    lines.append("## Top-level layout")
    lines.append("")
    if not summaries:
        lines.append("_No subdirectories detected — all source at repo root._")
        lines.append("")
    else:
        lines.append("| Path | Role (heuristic) | Files | Symbols | Languages |")
        lines.append("|---|---|---:|---:|---|")
        for s in summaries:
            role = s.role_hint or "_unknown_"
            langs = ", ".join(s.languages) if s.languages else "—"
            lines.append(
                f"| `{s.name}/` | {role} | {s.file_count} | {s.symbol_count} | {langs} |"
            )
        lines.append("")

    root_files = [
        f for f in files_map.files if "/" not in f.path
    ]
    if root_files:
        lines.append("## Repo-root files")
        lines.append("")
        for f in sorted(root_files, key=lambda x: x.path):
            lang = f.language or "—"
            lines.append(f"- `{f.path}` ({lang}, {f.size_bytes} bytes)")
        lines.append("")

    if doc_catalog is not None:
        arch_docs = _select_architecture_docs(doc_catalog)
        if arch_docs:
            lines.append("## Documented architecture")
            lines.append("")
            lines.append(
                "These checked-in docs describe the architecture. "
                "**Advisory only** — the AST-derived layout above is the "
                "source of truth. Each doc carries a `confidence` from "
                "`source-docs/INDEX.md`; treat low-confidence entries as "
                "history."
            )
            lines.append("")
            for d in arch_docs:
                title = f" — {d.title}" if d.title else ""
                lines.append(
                    f"- [`{d.path}`](../../{d.path}) "
                    f"(**{d.confidence}**{title})"
                )
            lines.append("")

    lines.append("## How to use this file")
    lines.append("")
    lines.append(
        "This is a fast-orienting overview. For specifics, walk `tree.json` "
        "for full hierarchy and consult `map/symbols.json` for exact line "
        "locations. Honor `conventions/naming.md` when adding new code in any "
        "of the directories above."
    )
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _group_files_by_top_level_dir(files_map: FilesMap) -> dict[str, list]:
    out: dict[str, list] = {}
    for f in files_map.files:
        head, _, _ = f.path.partition("/")
        if not _:
            continue  # root file, not in any dir
        out.setdefault(head, []).append(f)
    return out


def _group_symbols_by_top_level_dir(symbols_map: SymbolsMap) -> dict[str, list]:
    out: dict[str, list] = {}
    for s in symbols_map.symbols:
        head, _, _ = s.path.partition("/")
        if not _:
            continue
        out.setdefault(head, []).append(s)
    return out


def _role_hint_for(dirname: str) -> Optional[str]:
    return _DIR_ROLE_HINTS.get(dirname.lower())


# Filename signals that a doc is architecture-relevant. Case-insensitive
# substring match on the last path segment.
_ARCH_DOC_SIGNALS: tuple[str, ...] = (
    "architecture",
    "design",
    "overview",
    "system",
    "structure",
    "diagram",
)


def _select_architecture_docs(catalog: DocCatalog) -> list[DocEntry]:
    """Filter the catalog to docs that name architecture explicitly."""
    out: list[DocEntry] = []
    for d in catalog.docs:
        if d.is_external:
            continue
        name = d.path.rsplit("/", 1)[-1].lower()
        if any(sig in name for sig in _ARCH_DOC_SIGNALS):
            out.append(d)
            continue
        # Also match by H1 / H2 mentioning "architecture".
        if d.title and "architecture" in d.title.lower():
            out.append(d)
            continue
    # High-confidence first so the most useful pointer is at the top.
    confidence_order = {"high": 0, "medium": 1, "low": 2}
    out.sort(key=lambda d: (confidence_order.get(d.confidence, 3), d.path))
    return out


# --- playbooks/*.md ----------------------------------------------------------


_PLAYBOOK_BODIES: dict[str, str] = {
    "add-feature": """\
# Playbook — add a feature

Use this when the user asks to add a new capability that doesn't exist yet (page, endpoint, component, job, integration).

## 1. Confirm it's new
- Grep `map/symbols.json` for similar names. If you find a near-match, this might be an **update** (see `update.md` if present) rather than an addition.
- Check `tree.json` for a directory that already groups this kind of thing.

## 2. Decide where it goes
- Mirror an existing feature's location and structure. Find a peer feature in `tree.json`.
- Honor `conventions/naming.md`. Match casing for files, classes, functions, and methods.

## 3. Test first
- If `tests/` exists, write a test in the mirrored path before touching production code.
- Use the same test framework the rest of the project uses (look for pytest, jest, vitest, etc. in `PROJECT.md` or `map/files.json`).

## 4. Implement
- Start from the mirrored peer feature; change identifiers and adapt logic.
- Wire imports / routes / exports the same way the peer does it.

## 5. Verify and re-index
- Run the project's test command (look in `PROJECT.md` entry points or scripts).
- `dummyindex context rebuild --changed` to refresh the index against your edits.

## Common pitfalls
- Adding a duplicate of something that already exists (always check `map/symbols.json` first).
- Naming inconsistent with `conventions/naming.md`.
- Forgetting the export / registration step — find the existing wiring file in `tree.json`.
""",
    "add-endpoint": """\
# Playbook — add an HTTP endpoint

## 1. Find the existing endpoint pattern
- In `tree.json`, look for `api/`, `routes/`, `handlers/`, `controllers/`, or `webhooks/` directories.
- Pick a peer endpoint of the same kind (GET / POST / webhook / etc.) and read it.

## 2. Validate against project conventions
- File naming: see `conventions/naming.md`.
- Handler shape: mirror the peer's signature, error handling, response shape.

## 3. Inputs and outputs
- If a request/response schema exists (Pydantic, Zod, OpenAPI), define one for the new endpoint and add to whatever common schemas module is in use.
- For URL params and query strings, follow the project's typed-parsing pattern.

## 4. Auth and rate limits
- Check whether the peer endpoint uses an auth middleware / decorator. If yes, apply the same.
- Check for a rate-limit pattern (e.g. `@throttle`, `RateLimiter`) and apply if relevant.

## 5. Tests
- Mirror the peer's test file. Cover: happy path, validation failure, auth failure (if applicable), 5xx handling.

## 6. Register the route
- New endpoint must be importable / discoverable. Find where the peer endpoint is registered (router, blueprint, app.include_router, etc.) and add yours.

## 7. Re-index
- `dummyindex context rebuild --changed`
""",
    "add-migration": """\
# Playbook — add a database migration

## 1. Identify the migration tool
- Look for `alembic/`, `migrations/`, `prisma/`, `drizzle/`, `db/migrate/`, or similar in `tree.json`.
- Read the most recent migration to see naming and structure.

## 2. Generate the migration scaffold
- Use the project's tool (`alembic revision`, `prisma migrate dev`, `npx drizzle-kit generate`, etc.). Find the command in `PROJECT.md` or by inspecting the migration tool's config.

## 3. Write the schema change
- Up and down (or migrate / rollback). Both must be exercised.
- Match style of recent migrations: column-naming, defaults, indexes.

## 4. Update the corresponding model / schema
- Find the application-level model (`map/symbols.json` will have the class). Add the field / change with matching types.

## 5. Backfill if needed
- For non-null columns on existing tables, decide: backfill data first, then add NOT NULL? Add nullable and backfill in a follow-up?

## 6. Test
- If the project has a test database, run migrations against it in CI. Add a fixture covering the new state if a model assertion exists.

## 7. Re-index
- `dummyindex context rebuild --changed`

## Risks worth flagging to the user
- Migrations that lock tables for >100ms on large tables — call this out before merging.
- Schema changes without rollback paths.
""",
    "fix-bug": """\
# Playbook — fix a bug

## 1. Reproduce first
- Re-state the bug in your own words. If the symptom is unclear, ask the user one surgical question.
- Find the smallest set of inputs that reproduce it.

## 2. Locate the suspected code
- Search `map/symbols.json` for the symptom's surface (the API, the CLI, the UI handler).
- Walk inward via call sites — `tree.json` gives you parent/child structure; for cross-file callers, grep is fine.

## 3. Write a failing test
- Locate the project's test file for that module via `tree.json` or `map/files.json`.
- Add a test that fails with the current code and passes with the fix. This becomes the regression test.

## 4. Make the minimal fix
- Smallest possible change. No drive-by refactors.
- Honor `conventions/naming.md` — even one-line additions.

## 5. Verify
- Run the project's test suite.
- Confirm the failing test now passes; confirm no other tests broke.

## 6. Re-index
- `dummyindex context rebuild --changed`

## Anti-patterns
- "Fix" by wrapping the symptom in a try/except — root cause it.
- Removing the failing assertion instead of fixing the underlying code.
- Reformatting unrelated lines in the same PR.
""",
    "refactor": """\
# Playbook — refactor without behavior change

## 1. Set the boundary
- What's in scope (one symbol? a directory?). What's *not*.
- Write down the public surface that must not change.

## 2. Lock behavior with tests
- If the affected code lacks tests, add them *before* refactoring. Use `map/symbols.json` to find every entry point in scope.
- Tests should fail if behavior changes — that's the whole point.

## 3. Make the refactor in small, reversible steps
- Rename → move → extract → re-organize. One commit per kind of change is easier to review.
- After each step, run tests. Stop at the first regression.

## 4. Honor conventions
- `conventions/naming.md` applies to new names introduced by the refactor (extracted helpers, renamed symbols).

## 5. Re-index after each substantive step
- `dummyindex context rebuild --changed` — keeps the index honest as you move things around.

## 6. Verify the public surface
- For each item in your "must not change" list, manually confirm it still matches.

## Anti-patterns
- Sneaking behavior changes into a "refactor" PR.
- Renaming things en masse without checking call sites.
- Skipping the tests-first step.
""",
}


PLAYBOOK_IDS: tuple[str, ...] = tuple(sorted(_PLAYBOOK_BODIES))


def generate_playbook_md(playbook_id: str) -> str:
    if playbook_id not in _PLAYBOOK_BODIES:
        raise KeyError(
            f"unknown playbook '{playbook_id}'; available: "
            f"{', '.join(PLAYBOOK_IDS)}"
        )
    return _PLAYBOOK_BODIES[playbook_id]


# --- Writers -----------------------------------------------------------------


def write_how_to_use_md(path: Path) -> None:
    _atomic_write(path, generate_how_to_use_md())


def write_architecture_overview_md(
    path: Path,
    repo_root: Path,
    files_map: FilesMap,
    symbols_map: SymbolsMap,
    meta: Meta,
    *,
    doc_catalog: Optional[DocCatalog] = None,
) -> None:
    _atomic_write(
        path,
        generate_architecture_overview_md(
            repo_root, files_map, symbols_map, meta, doc_catalog=doc_catalog
        ),
    )


def write_playbook_md(path: Path, playbook_id: str) -> None:
    _atomic_write(path, generate_playbook_md(playbook_id))


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)
